version = 0.1
[default.deploy.parameters]
stack_name = "aegis-production"
resolve_s3 = true
s3_prefix = "aegis"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment = \"production\" ChaosSchedule = \"cron(0 */6 * * ? *)\""

[staging.deploy.parameters]
stack_name = "aegis-staging"
resolve_s3 = true
s3_prefix = "aegis-staging"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment = \"staging\" ChaosSchedule = \"cron(0 0 * * ? *)\""

[development.deploy.parameters]
stack_name = "aegis-development"
resolve_s3 = true
s3_prefix = "aegis-dev"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment = \"development\" ChaosSchedule = \"cron(0 8 * * ? *)\""
